# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b66d6c7e241d65291aca939db16a5941d6bdb04d5340dd1c8889fb8f94f26c9c449af6bb38cd1671f77d059f058d0dfbffed0ba48eb6d17aab5fc26a714d4b1

test:
  secret_key_base: 863b667d723fe12d3c71d820d535f3075ec2385f2a546161e15683cb43833e0a31c173edfc11172fcf1769745f0c52857950bdd372a07aa4bd4897371960a928

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
